// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciruhybcksuzcrmygktz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcnVoeWJja3N1emNybXlna3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDU3MDYsImV4cCI6MjA2NTIyMTcwNn0.rQLKcll6FpZ4xzJ7Y9Q2s98A8bw30l9iuvwLbGwk2bM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);